(defun cibin-load-all-custom-bindings ()
(interactive)
  (message "loading all")
(load-file "~/.emacs.d/my-files/config/personal-configs/functions.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/shell.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/my-python.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/navigation.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/move-copy.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/cbn-compile.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/search-bindings.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/dired-settings.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/dired-settings2.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/more-custom-functions.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/auto-complete.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/org-settings.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/buttonize-buffer.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/other-settings.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/appearance.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/auto-spell.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/tabbar-tweaks.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/major-mode-settings.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/cbn-mode-line.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/cbn-mode-line2.el")

(load-file "~/.emacs.d/my-files/config/personal-configs/xah-fly-keys-functions.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/added-april.el")
; (load-file "~/.emacs.d/my-files/config/personal-configs/cbn-xah-fly-keys.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/hydra.el")
(cibin-load-essential-custom-bindings)
(message "loaded all")
  )
  
 (defun cibin-load-essential-custom-bindings ()
(interactive)
  (message "loading all")
(load-file "~/.emacs.d/my-files/config/personal-configs/buffer-management.el")
(load-file "~/.emacs.d/my-files/config/personal-configs/starter-kit-bindings.el")
  
 )

(cibin-load-all-custom-bindings)
(global-set-key (kbd "M-5" ) 'cibin-load-all-custom-bindings)
(global-set-key (kbd "M-6" ) 'cibin-load-essential-custom-bindings)
